parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\UI\Controller\:
        resource: '../src/UI/Controller'
        tags: ['controller.service_arguments']

    App\UI\Command\:
        resource: '../src/UI/Command'
        autowire: true
        autoconfigure: true
        bind:
            $commandBus: '@broadway.command_handling.command_bus'
            $budgetRepository: '@App\Domain\Budget\BudgetRepository'

    App\Infrastructure\:
        resource: '../src/Infrastructure'
        autowire: true
        autoconfigure: true

    App\Domain\Budget\Command\BudgetCommandHandler:
        arguments:
            $budgetRepository: '@App\Domain\Budget\BudgetRepository'
        tags:
            - { name: broadway.command_handler }

    App\Domain\Budget\BudgetRepository:
        arguments:
            $eventStore: '@broadway.event_store'
            $eventBus: '@broadway.event_handling.event_bus'
            $eventStreamDecorators: ['@broadway.metadata_enriching_event_stream_decorator']
