services:
    App\ReadModel\BudgetBalance\BudgetBalanceProjector:
        tags:
            - { name: broadway.domain.event_listener }
        arguments:
            $readModelRepository: '@app.readmodel.repository.budgetbalance'

    app.readmodel.repository.budgetbalance:
        class: 'Broadway\ReadModel\ReadModel'
        factory: ['@broadway.read_model.repository_factory', create]
        arguments:
             $name: 'app.budgetbalance'
             $class: 'App\ReadModel\BudgetBalance\BudgetBalanceProjector'

